### YamlMime:ManagedReference
items:
- uid: Runly.ConfigReader
  commentId: T:Runly.ConfigReader
  id: ConfigReader
  parent: Runly
  children:
  - Runly.ConfigReader.#ctor(Runly.Hosting.JobCache)
  - Runly.ConfigReader.FromFile(System.String)
  - Runly.ConfigReader.FromJson(System.String)
  langs:
  - csharp
  - vb
  name: ConfigReader
  nameWithType: ConfigReader
  fullName: Runly.ConfigReader
  type: Class
  source:
    id: ConfigReader
    path: /github/workspace/src/Runly/ConfigReader.cs
    startLine: 15
  assemblies:
  - Runly
  namespace: Runly
  summary: "\nDeserializes JSON config files into instances of <xref href=\"Runly.Config\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class ConfigReader : object'
    content.vb: >-
      Public Class ConfigReader
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Runly.ConfigReader.#ctor(Runly.Hosting.JobCache)
  commentId: M:Runly.ConfigReader.#ctor(Runly.Hosting.JobCache)
  id: '#ctor(Runly.Hosting.JobCache)'
  parent: Runly.ConfigReader
  langs:
  - csharp
  - vb
  name: ConfigReader(JobCache)
  nameWithType: ConfigReader.ConfigReader(JobCache)
  fullName: Runly.ConfigReader.ConfigReader(Runly.Hosting.JobCache)
  type: Constructor
  source:
    id: .ctor
    path: /github/workspace/src/Runly/ConfigReader.cs
    startLine: 23
  assemblies:
  - Runly
  namespace: Runly
  summary: "\nInitializes a new <xref href=\"Runly.ConfigReader\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public ConfigReader(JobCache cache)
    parameters:
    - id: cache
      type: Runly.Hosting.JobCache
      description: The <xref href="Runly.Hosting.JobCache" data-throw-if-not-resolved="false"></xref> containing the config types that can be read.
    content.vb: Public Sub New(cache As JobCache)
  overload: Runly.ConfigReader.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Runly.ConfigReader.FromFile(System.String)
  commentId: M:Runly.ConfigReader.FromFile(System.String)
  id: FromFile(System.String)
  parent: Runly.ConfigReader
  langs:
  - csharp
  - vb
  name: FromFile(String)
  nameWithType: ConfigReader.FromFile(String)
  fullName: Runly.ConfigReader.FromFile(System.String)
  type: Method
  source:
    id: FromFile
    path: /github/workspace/src/Runly/ConfigReader.cs
    startLine: 33
  assemblies:
  - Runly
  namespace: Runly
  summary: "\nCreates an instance of a <xref href=\"Runly.Config\" data-throw-if-not-resolved=\"false\"></xref> from the JSON file found at <code data-dev-comment-type=\"paramref\" class=\"paramref\">path</code>.\n"
  example: []
  syntax:
    content: public Config FromFile(string path)
    parameters:
    - id: path
      type: System.String
      description: A file path contianing a JSON config.
    return:
      type: Runly.Config
      description: An instance of <xref href="Runly.Config" data-throw-if-not-resolved="false"></xref> from the deserialized file.
    content.vb: Public Function FromFile(path As String) As Config
  overload: Runly.ConfigReader.FromFile*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Runly.ConfigReader.FromJson(System.String)
  commentId: M:Runly.ConfigReader.FromJson(System.String)
  id: FromJson(System.String)
  parent: Runly.ConfigReader
  langs:
  - csharp
  - vb
  name: FromJson(String)
  nameWithType: ConfigReader.FromJson(String)
  fullName: Runly.ConfigReader.FromJson(System.String)
  type: Method
  source:
    id: FromJson
    path: /github/workspace/src/Runly/ConfigReader.cs
    startLine: 56
  assemblies:
  - Runly
  namespace: Runly
  summary: "\nCreates an instance of a <xref href=\"Runly.Config\" data-throw-if-not-resolved=\"false\"></xref> from the JSON string.\n"
  example: []
  syntax:
    content: public Config FromJson(string json)
    parameters:
    - id: json
      type: System.String
      description: A string containing a JSON config.
    return:
      type: Runly.Config
      description: An instance of <xref href="Runly.Config" data-throw-if-not-resolved="false"></xref> from the deserialized string.
    content.vb: Public Function FromJson(json As String) As Config
  overload: Runly.ConfigReader.FromJson*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Runly.Config
  commentId: T:Runly.Config
  parent: Runly
  name: Config
  nameWithType: Config
  fullName: Runly.Config
- uid: Runly
  commentId: N:Runly
  name: Runly
  nameWithType: Runly
  fullName: Runly
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Runly.ConfigReader
  commentId: T:Runly.ConfigReader
  name: ConfigReader
  nameWithType: ConfigReader
  fullName: Runly.ConfigReader
- uid: Runly.Hosting.JobCache
  commentId: T:Runly.Hosting.JobCache
  parent: Runly.Hosting
  name: JobCache
  nameWithType: JobCache
  fullName: Runly.Hosting.JobCache
- uid: Runly.ConfigReader.#ctor*
  commentId: Overload:Runly.ConfigReader.#ctor
  name: ConfigReader
  nameWithType: ConfigReader.ConfigReader
  fullName: Runly.ConfigReader.ConfigReader
- uid: Runly.Hosting
  commentId: N:Runly.Hosting
  name: Runly.Hosting
  nameWithType: Runly.Hosting
  fullName: Runly.Hosting
- uid: Runly.ConfigReader.FromFile*
  commentId: Overload:Runly.ConfigReader.FromFile
  name: FromFile
  nameWithType: ConfigReader.FromFile
  fullName: Runly.ConfigReader.FromFile
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Runly.ConfigReader.FromJson*
  commentId: Overload:Runly.ConfigReader.FromJson
  name: FromJson
  nameWithType: ConfigReader.FromJson
  fullName: Runly.ConfigReader.FromJson
