name: Nuget
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package Core
        run: dotnet pack src/Core/Core.csproj -c Release -o .

      - name: Package Client
        run: dotnet pack src/Client/Client.csproj -c Release -o .

      - name: Package Runly
        run: dotnet pack src/Runly/Runly.csproj -c Release -o .

      - name: Package Templates
        run: dotnet pack src/Templates/Templates.csproj -c Release -o .

      - name: Push to Nuget
        run: find . -name 'Runly*.nupkg' | xargs -i dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
